import { MoralisNextApi } from "@moralisweb3/next";
export default MoralisNextApi({
    apiKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjE4NTg1MWIyLTg4NDgtNGQ4Mi04MDEzLWQzM2IyMmFmYWQxMyIsIm9yZ0lkIjoiMzQ0MTEzIiwidXNlcklkIjoiMzUzNzQ0IiwidHlwZUlkIjoiY2E1MzQ4YTYtMmIzNS00YzkwLTk5ZWEtNmIwN2M1MWYzMTg2IiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE2ODcwOTYxNzYsImV4cCI6NDg0Mjg1NjE3Nn0.eKicRzkgUdpycHEBtvcr-YBaSRqWvZYTYjE1LW7YIEc",
});
