import './globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'User Dashboard',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <section >{children}</section>
  )
}